development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: DE_train_05_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: DE_train_05_production
