# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69cfae184bcb04e970432de88fee5deae8dc1f4af86f1dd91a74cd07629e8cf49d9e27af0b59ac0eed4ff5d3ffccd56c7d15bb33affa2316ee68092e3b59b6c1

test:
  secret_key_base: 52fef30194692a649c656a451326ea48c4a1282dfee383bc3bb7ff261e3b583b7fdb6b7c222736aae19436d612d27f48ce4c4e9d634170ddf0fbbcd104539c4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
